### ISSUE TITLE
Biestable D  error en nuevo diseño

### ISSUE THREAD

**Issue by RCTepperN** [LogisimIt/Logisim#1]
Las entradas de preset 1 y preset 0 dibujan equivocadamente los inversores.
Cuando los inversores estan presentes, para deshabilitarlos se deben conectar a 1. Ocurre justo lo contrario.

**Comment by AndreaNeti** [comment]
If you are talking about flip flops I've already fixed it in the early
branch and it will come in the next update

Il 16 Feb 2018 23:42, "RCTepperN" <notifications@github.com> ha scritto:

Las entradas de preset 1 y preset 0 dibujan equivocadamente los inversores.
Cuando los inversores estan presentes, para deshabilitarlos se deben
conectar a 1. Ocurre justo lo contrario.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LogisimIt/Logisim/issues/1>, or mute the thread

**Comment by RCTepperN** [comment]
Thankyou for your excelent software and answer.
Saludos,
Ricardo Tepper


2018-02-16 20:03 GMT-03:00 LogisimIt <notifications@github.com>:

**Comment by AndreaNeti** [comment]
You're welcome

Il 23 Feb 2018 20:24, "RCTepperN" <notifications@github.com> ha scritto:
