### ISSUE TITLE
Errores según posición en grilla

### ISSUE THREAD

**Issue by RCTepperN** [LogisimIt/Logisim#2]
Sucede que moviendo elementos (inversores, biestables D) señales que estaban bien se convierten en errores (rojas). Eventualmente desplazando los elementos algunos cuadros en la grilla el error puede desaparecer.
Version 2.13.0.0

**Comment by AndreaNeti** [comment]
Yes, I know, It's a bug afflicting also the original Logisim and it's very
difficult to fix because I can't understand where it's failing. You could
bypass this also with reset and re-enable simulation (you can do this combo
faster with f5)
The code is neither commented, I'll try to do my best but I think only Carl
Burch can do this

Il 16 Feb 2018 23:53, "RCTepperN" <notifications@github.com> ha scritto:

**Comment by RCTepperN** [comment]
Thankyou for your tip. It works fine.
Best regards,
Ricardo Tepper


2018-02-16 19:59 GMT-03:00 LogisimIt <notifications@github.com>:
