### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ghadjich** [LogisimIt/Logisim#21]
Dear Team,

I updated logisim ITA and the tutorial is no longer working (Help - tutorial). I use it in class with my students. Can you please correct the issue?

Thank you,
George

**Comment by AndreaNeti** [comment]
We are aware of this problem, a fix will come in the next update.Meanwhile you can use the tutorial from the original logisim website: http://www.cburch.com/logisim/docs/2.7/en/html/guide/tutorial/index.html Thanks for the report  :)Da: ghadjichInviato: venerdì 8 ottobre 2021 13:00A: Logisim-Ita/LogisimCc: SubscribedOggetto: [Logisim-Ita/Logisim] Tutorial (#21) Dear Team,I updated logisim ITA and the tutorial is no longer working (Help - tutorial). I use it in class with my students. Can you please correct the issue?Thank you,George—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghadjich** [comment]
Thank you very much!
